### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by cksachdev** [int3h/SublimeFixMacPath#11]
I tried to install it from Package Manager, but it didn't created any menu entry or directory in the Packages folder. Then after cloning the repo in Packages directory, I can see the package is loaded.

```
reloading plugin FixMacPath.FixPath
reloading plugin Gulp.base_command
reloading plugin Gulp.cross_platform_codecs
reloading plugin Gulp.gulp
reloading plugin Gulp.progress_notifier
```

But when I try to run Gulp, I still get the errors

```
Running 'build'...

module.js:340
    throw err;
          ^
Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/bin/gulp:4:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Is there any way to check and run the commands directly in sublime, to make sure that it has detected the right versions and environment variables needed to run Gulp?

**Comment by sailormoon** [comment]
Hi @cksachdev, I am unsure if int3h is still maintaining this.  I started off creating a branch of this to fix all the issues but ended up overhauling most of the project and created a separate repository.  If you want to give it a shot, it is located here: https://github.com/sailorswift/Envy

It has the same functionality as this project except it includes all of the environment variables from the specified shell.  I'll fix any issues you have ASAP.  Thanks for your time! :smile:

**Comment by cksachdev** [comment]
Thanks for your response. I removed SublimeFixMacPath and installed Envy from Package Manager. I am still getting the same error.
![Screenshot](https://docs.google.com/uc?id=0Bz_3NOSxzC7NMS1fYkMtbVhtYVU)

I tried to change the shell but I am getting error. refer to the screenshot above.

**Comment by Gr1N** [comment]
@cksachdev you can try my very simple plugin (https://github.com/Gr1N/SublimeFixMacEnv) to solve your problem.
